### ISSUE TITLE
A way to randomize the clicks?

### ISSUE THREAD

**Issue by TrickyVicky4** [purpxd/E7AutoShop#2]
Hello! I was wondering if it's possible for you can make the script randomize the clicks in the area to reduce suspicion. Thanks!

**Comment by purpxd** [comment]
> Hello! I was wondering if it's possible for you can make the script randomize the clicks in the area to reduce suspicion. Thanks!

E7 doesn't track user interaction patterns with the application. Doing so requires implementing a system to track these patterns and storing that information. The users that would target is so slim, it wouldn't be worth it and in the end it helps the game anyways because we are spending more resources. I know this because I've been using built in emulator macro's for a very long time before creating this app and similar software has existed before this one and they never touched the ban list. But if it makes you more comfortable to use the program then I may add it in on the next update

**Comment by TrickyVicky4** [comment]
> But if it makes you more comfortable to use the program then I may add it in on the next update

If it's no inconvenience to you then that would be great. There can be a toggle for it too if needed. If it's too much of a hassle then please don't mind my paranoia. Thank you for the response.

**Comment by K3imp** [comment]
Hey, I was wondering if this feature could be added too. 

Thanks for sharing this macro it's actually really smooth and runs well on my pc!

**Comment by purpxd** [comment]
Hello, I’ll try to push the update sometime this week. You’re welcome!
