### ISSUE TITLE
Input port number

### ISSUE THREAD

**Issue by pwongsut** [purpxd/E7AutoShop#6]
Can you add a way to input adb port number manually?
I see that you have some commented code related to this in the installer version (v1.3)
Also I think the installer version is not the same as in the main branch.

**Comment by purpxd** [comment]
> Also I think the installer version is not the same as in the main branch.

Hello,

The repository version and the current released versions are indeed not the same. As far as adding the option to include the port number. I initially had that option open because I thought Blue Stacks required a port number. But it actually didn't, so I removed it. Are you having issues getting the program to interact with your emulator?
